// ***** THIS FILE IS INCLUDED AUTOMATICALLY VIA MAKE *****
// DO NOT edit this file in /src, instead edit /cfg_install/system.rs.

// The wrapper will set the LD_PRELOAD environment variable to this path.
#[macro_export]
macro_rules! so_path {
    () => {
        "/usr/lib/nsod/libnsod_open_hook.so"
    };
}

// Path to the directory holding the systemwide inject.json and wrapper.json files.
#[macro_export]
macro_rules! base_cfg_dir_path {
    () => {
        "/etc/nsod"
    };
}

// Path to the directory holding the text data for the cli app.
#[macro_export]
macro_rules! base_ui_dir_path {
    () => {
        "/usr/lib/nsod/ui"
    };
}

// Path to the basic help file.
#[macro_export]
macro_rules! usage_path {
    () => {
        "/usr/lib/nsod/ui/en/usage.txt"
    };
}

// Path to the advanced help file.
#[macro_export]
macro_rules! help_path {
    () => {
        "/usr/lib/nsod/ui/en/README.txt"
    };
}