// ***** THIS FILE IS INCLUDED AUTOMATICALLY VIA MAKE *****
// DO NOT edit this file in /src, instead edit /cfg_install/user.rs.

// The wrapper will set the LD_PRELOAD environment variable to this path.
#[macro_export]
macro_rules! so_path {
    () => {
        {
            let home = std::env::home_dir().expect("NSOD: Failed to find home directory.");
            let home_str = home.to_str().unwrap();
            format!("{home_str}/.nsod/lib/libnsod_open_hook.so")
        }
    };
}

// Path to the directory holding the user's inject.json and wrapper.json files.
#[macro_export]
macro_rules! base_cfg_dir_path {
    () => {
        {
            let home = std::env::home_dir().expect("NSOD: Failed to find home directory.");
            let home_str = home.to_str().unwrap();
            format!("{home_str}/.nsod/cfg")
        }
    };
}

// Path to the directory holding the text data for the cli app.
#[macro_export]
macro_rules! base_ui_dir_path {
    () => {
        {
            let home = std::env::home_dir().expect("NSOD: Failed to find home directory.");
            let home_str = home.to_str().unwrap();
            format!("{home_str}/.nsod/lib/ui")
        }
    };
}

// Path to the basic help file.
#[macro_export]
macro_rules! usage_path {
    () => {
        {
            let home = std::env::home_dir().expect("NSOD: Failed to find home directory.");
            let home_str = home.to_str().unwrap();
            format!("{home_str}/.nsod/lib/ui/en/usage.txt")
        }
    };
}

// Path to the advanced help file.
#[macro_export]
macro_rules! help_path {
    () => {
        {
            let home = std::env::home_dir().expect("NSOD: Failed to find home directory.");
            let home_str = home.to_str().unwrap();
            format!("{home_str}/.nsod/lib/ui/en/README.txt")
        }
    };
}